name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Deno
        run: |
        console/install_deno
        export DENO_INSTALL="/home/runner/.deno"
        export PATH="$DENO_INSTALL/bin:$PATH"
      - name: Unit
        run: |
          deno test tests/test.ts --config tsconfig.json --allow-net
      - name: Create APP
        run: |
          deno test tests/create_app_test.ts --allow-read --allow-write --allow-run
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh
      - name: Formatter
        run: $HOME/.deno/bin/deno fmt --check
