name: master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Dexter
        run: deno test --allow-env --allow-net dexter/tests/

      - name: Paladin
        run: deno test --allow-env --allow-net paladin/tests/

      - name: CSRF
        run: |
          cd csrf/tests
          deno test --allow-net --allow-env --config tsconfig.json

      - name: Cors
        run: deno test -A cors/tests

  linter:
    # Only one OS is required since fmt is cross platform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Deno
        uses: denolib/setup-deno@master

      - name: Formatter
        run: deno fmt --check
